(() => {
  const form = document.getElementById('contact-form');
  const typeField = document.getElementById('contact-type');
  const workWrap = document.getElementById('contact-work-wrap');
  const workField = document.getElementById('contact-work');
  const messageField = document.getElementById('contact-message');
  const status = document.getElementById('contact-status');
  const dialog = document.getElementById('work-dialog');
  const menuToggle = document.querySelector('.menu-toggle');
  const menuIcon = menuToggle?.querySelector('i');
  const targetEmail = 'matrafiscdance@gmail.com';

  function updateWorkField() {
    const isWork = typeField?.value === 'Work enquiry';
    if (workWrap) workWrap.hidden = !isWork;
    if (workField) workField.required = Boolean(isWork);
    if (!isWork && workField) workField.value = '';
  }

  function fillEnquiry(type, work = '') {
    if (!form || !typeField) return;

    const available = [...typeField.options].some(option => option.value === type);
    typeField.value = available ? type : 'General enquiry';
    updateWorkField();

    if (type === 'Work enquiry' && workField) {
      const workExists = [...workField.options].some(option => option.value === work);
      workField.value = workExists ? work : '';
      if (messageField && !messageField.value.trim()) {
        messageField.value = work
          ? `Hello Matrafisc Dance,\n\nI'm interested in ${work} and would like to enquire about presenting, programming or learning more about this work.\n\n`
          : `Hello Matrafisc Dance,\n\nI'd like to enquire about one of your works.\n\n`;
      }
    } else if (messageField && !messageField.value.trim()) {
      const prompts = {
        'Touring / programming': `Hello Matrafisc Dance,\n\nI'd like to discuss programming or touring opportunities with the company.\n\n`,
        'Collaboration': `Hello Matrafisc Dance,\n\nI'd like to discuss a potential collaboration with the company.\n\n`,
        'Workshop / education': `Hello Matrafisc Dance,\n\nI'd like to enquire about a workshop, educational project or residency.\n\n`,
        'Press / media': `Hello Matrafisc Dance,\n\nI'd like to make a press or media enquiry.\n\n`
      };
      messageField.value = prompts[type] || '';
    }

    if (status) {
      status.textContent = type === 'Work enquiry' && work
        ? `Enquiry prepared for ${work}. Add your details and message, then send.`
        : 'Enquiry details have been prefilled. Add your contact details and message, then send.';
      status.className = 'contact-status is-ready';
    }

    if (dialog?.open) dialog.close();
    document.body.classList.remove('dialog-open');

    requestAnimationFrame(() => {
      document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      window.setTimeout(() => document.getElementById('contact-name')?.focus({ preventScroll: true }), 450);
    });
  }

  document.addEventListener('click', event => {
    const trigger = event.target.closest('[data-enquiry]');
    if (!trigger) return;
    event.preventDefault();
    fillEnquiry(trigger.dataset.enquiry || 'General enquiry', trigger.dataset.workTitle || '');
  });

  typeField?.addEventListener('change', updateWorkField);
  updateWorkField();

  form?.addEventListener('submit', event => {
    event.preventDefault();

    if (!form.checkValidity()) {
      form.reportValidity();
      if (status) {
        status.textContent = 'Please complete the required fields before sending your enquiry.';
        status.className = 'contact-status is-error';
      }
      return;
    }

    const data = new FormData(form);
    const name = String(data.get('name') || '').trim();
    const email = String(data.get('email') || '').trim();
    const type = String(data.get('enquiryType') || 'General enquiry').trim();
    const work = String(data.get('work') || '').trim();
    const message = String(data.get('message') || '').trim();

    const subject = work
      ? `Matrafisc Dance — ${type} — ${work}`
      : `Matrafisc Dance — ${type}`;

    const body = [
      `Name: ${name}`,
      `Email: ${email}`,
      `Enquiry type: ${type}`,
      work ? `Work: ${work}` : '',
      '',
      message
    ].filter((line, index, array) => line !== '' || (index > 0 && array[index - 1] !== '')).join('\n');

    if (status) {
      status.textContent = 'Your email app is opening with the enquiry details prepared.';
      status.className = 'contact-status is-ready';
    }

    window.location.href = `mailto:${targetEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  });

  // Existing work dialogs are generated by script.js. Enhance their enquiry link after each render
  // so it uses the shared contact form and carries the correct work title.
  const dialogContent = document.getElementById('dialog-content');
  if (dialogContent && 'MutationObserver' in window) {
    const observer = new MutationObserver(() => {
      const enquiry = dialogContent.querySelector('.dialog-enquire');
      const title = dialogContent.querySelector('#dialog-title')?.textContent?.trim() || '';
      if (!enquiry) return;
      enquiry.href = '#contact';
      enquiry.dataset.enquiry = 'Work enquiry';
      enquiry.dataset.workTitle = title;
      enquiry.innerHTML = `Enquire about this work <i class="fa-solid fa-arrow-right" aria-hidden="true"></i>`;
    });
    observer.observe(dialogContent, { childList: true, subtree: true });
  }

  // Keep the Font Awesome mobile menu icon in sync with the existing menu state.
  menuToggle?.addEventListener('click', () => {
    requestAnimationFrame(() => {
      const open = document.body.classList.contains('menu-open');
      menuIcon?.classList.toggle('fa-bars', !open);
      menuIcon?.classList.toggle('fa-xmark', open);
    });
  });

  document.querySelectorAll('.site-nav a').forEach(link => link.addEventListener('click', () => {
    menuIcon?.classList.add('fa-bars');
    menuIcon?.classList.remove('fa-xmark');
  }));

  // Optional query-string prefill makes direct campaign links possible, e.g.
  // ?enquiry=work&work=Bruise#contact
  const params = new URLSearchParams(window.location.search);
  const queryType = params.get('enquiry');
  const queryWork = params.get('work');
  if (queryType) {
    const typeMap = {
      work: 'Work enquiry',
      touring: 'Touring / programming',
      collaboration: 'Collaboration',
      workshop: 'Workshop / education',
      press: 'Press / media',
      general: 'General enquiry'
    };
    fillEnquiry(typeMap[queryType.toLowerCase()] || 'General enquiry', queryWork || '');
  }
})();
